"""Generate a Markdown QC report from a summary dict and the produced plots."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from . import __version__

PLOT_TITLES = {
    "length_histogram": "Length distribution",
    "gc_histogram": "GC content distribution",
    "per_base_quality": "Per-base mean quality",
}


def _table(rows: Iterable[tuple[str, object]]) -> str:
    lines = ["| Metric | Value |", "| --- | --- |"]
    for name, value in rows:
        lines.append(f"| {name} | {value} |")
    return "\n".join(lines)


def _fastq_rows(summary: dict) -> list[tuple[str, object]]:
    rows: list[tuple[str, object]] = [
        ("Total reads", f"{summary['total_reads']:,}"),
        ("Total bases", f"{summary['total_bases']:,}"),
        ("Min read length", summary["min_read_length"]),
        ("Max read length", summary["max_read_length"]),
        ("Mean read length", summary["mean_read_length"]),
        ("Mean GC content", f"{summary['mean_gc_content'] * 100:.2f}%"),
        ("Mean Phred quality", summary["mean_phred_quality"]),
    ]
    for key in sorted(k for k in summary if k.startswith("reads_below_q") and not k.endswith("_pct")):
        threshold = key.replace("reads_below_q", "")
        pct_key = f"{key}_pct"
        rows.append(
            (f"Reads below Q{threshold}",
             f"{summary[key]:,} ({summary.get(pct_key, 0)}%)")
        )
    return rows


def _fasta_rows(summary: dict) -> list[tuple[str, object]]:
    return [
        ("Total sequences", f"{summary['total_sequences']:,}"),
        ("Min sequence length", summary["min_sequence_length"]),
        ("Max sequence length", summary["max_sequence_length"]),
        ("Mean sequence length", summary["mean_sequence_length"]),
        ("N50", summary["n50"]),
        ("Mean GC content", f"{summary['mean_gc_content'] * 100:.2f}%"),
        ("Total bases", f"{summary['total_bases']:,}"),
        ("N bases", f"{summary['n_base_count']:,} ({summary['n_base_pct']}%)"),
    ]


def render_markdown_report(
    summary: dict,
    plot_paths: list[Path],
    input_file: Path,
    outdir: Path,
) -> Path:
    """Write final_report.md and return its path.

    Plot paths are referenced relative to the report so the rendered Markdown
    works when the output directory is moved or zipped.
    """
    kind = summary.get("file_kind", "unknown").upper()
    rows = _fastq_rows(summary) if kind == "FASTQ" else _fasta_rows(summary)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    parts: list[str] = []
    parts.append(f"# OmicsQC Report — {input_file.name}")
    parts.append("")
    parts.append(f"- **Input file:** `{input_file}`")
    parts.append(f"- **File type:** {kind}")
    parts.append(f"- **Generated:** {timestamp}")
    parts.append(f"- **OmicsQC version:** {__version__}")
    parts.append("")
    parts.append("## Summary metrics")
    parts.append(_table(rows))
    parts.append("")

    if plot_paths:
        parts.append("## Plots")
        for p in plot_paths:
            try:
                rel = p.relative_to(outdir).as_posix()
            except ValueError:
                rel = p.name
            heading = PLOT_TITLES.get(p.stem, p.stem.replace("_", " ").capitalize())
            parts.append(f"### {heading}")
            parts.append(f"![{p.stem}]({rel})")
            parts.append("")

    parts.append("---")
    parts.append("Generated by OmicsQC — a lightweight FASTQ/FASTA QC toolkit.")

    report_path = outdir / "final_report.md"
    report_path.write_text("\n".join(parts), encoding="utf-8")
    return report_path
